# Generated by Django 5.1.4 on 2025-01-14 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('completed', 'Completed')], default='created', max_length=50),
        ),
    ]
