# Generated by Django 5.1.4 on 2025-01-29 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certification_app', '0004_document_file_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
    ]
